global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '7781197690:AAFjtr3DKsz1rpOGgX-02v_pmt-zkHGV3Iw'  # Замените на ваш токен бота
    chat_id: 435844411  # Замените на ваш ID чата
    parse_mode: 'HTML'
    message: |
      <b>{{ .Status | toUpper }}</b>
      <b>Алерт:</b> {{ .CommonAnnotations.summary }}
      <b>Описание:</b> {{ .CommonAnnotations.description }}
      <b>Начало:</b> {{ .StartsAt | date "02.01.2006 15:04:05" }}
      {{ if ne .Status "firing" }}
      <b>Завершение:</b> {{ .EndsAt | date "02.01.2006 15:04:05" }}
      {{ end }}
